config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: "confirmations",
    omniauth_callbacks: "callbacks"
  }

  as :user do
    get "/login" => "devise/sessions#new", as: :login
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy", as: :logout
    get "/signup" => "devise/registrations#new", as: :signup
    post "/signup" => "devise/registrations#create"
  end

  resources :users do
    member do
      get :favorites
      resources :followers, only: :index
      resources :followings, only: :index
      resources :activities, only: :index
    end
  end
  root "static_pages#home"
  namespace :admin do
    resources :books
    resources :categories
    resources :requests, only: [:index, :update, :show]
    resources :authors
    resources :import, only: :create
    resources :publishers
    resources :users
    get "", to: "dashboard#home", as: "/"
  end
  resources :books do
    member do
      resources :borrows, only: [:new, :create]
    end
  end
  resources :favorites, only: [:create, :destroy]
  resources :requests
  resources :categories, only: [:show]
  resources :reviews, except: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :comments, except: :index
  resources :likes, only: [:create, :destroy, :show]
  resources :bookmarks, only: [:create, :update]
  resources :messages, only: [:index]
  resources :chatrooms
  resources :notifications, only: [:index, :update]
  mount ActionCable.server => "/cable"
end

app/models/book.rb
class Book < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  scope :search, -> (condition) {where("title LIKE :search", search: "%#{condition}%")}
  scope :latest, -> {order(created_at: :desc)}

  belongs_to :category
  belongs_to :author
  belongs_to :publisher

  has_many :favorites, dependent: :destroy
  has_many :favorited_by, through: :favorites, source: :user
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_by, through: :bookmarks, source: :user, dependent: :destroy
  has_many :reviewed_by, through: :reviews, source: :user, dependent: :destroy
  has_many :specifications, dependent: :destroy
  has_many :borrows, dependent: :destroy
  has_many :borrowed_by, through: :borrows, source: :user, dependent: :destroy

  validates :title, presence: true, length: {maximum: 150}, allow_nil: false
  validates :publish_date, presence: true

  validate :specifications, if: :exceed_specification?
  validates :pages, presence: true, numericality: {only_integer: true}
  accepts_nested_attributes_for :specifications, reject_if: :all_blank, allow_destroy: true

  def avg_rating
    avg = self.reviews.average(:rate)
    avg.nil? ? avg = 0 : avg.truncate(2).to_s('F').to_f.round
  end

  def available_borrow?
    !self.borrows.collect(&:borrowing?).any?
  end

  private
  def exceed_specification?
    (1..5) === self.specifications.size
  end

end

app/models/supports/book.rb
class Supports::Book
  attr_reader :book

  def initialize book
    @book = book
  end

  def borrowed
    @book.borrows.where(status: :borrowing).first
  end

  def queues
    @book.borrows.where(status: :awaiting).order("start_date").limit(3)
  end

  def user_bookmark current_user
    current_user.get_bookmark @book
  end

  def reviews
    @book.reviews
  end

end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :authenticate_user!, :admin_user
  load_and_authorize_resource

  layout "admin"

  include BooksHelper

  before_action :load_book, only: [:destroy, :update]
  before_action :load_relationships, except: [:index]

  def index
    if params[:filter]
      @books = filter_by(params[:filter]).latest.paginate page: params[:page], per_page: Settings.item_per_page
    else params[:search]
      @books = search_by(params[:search]).latest.paginate page: params[:page], per_page: Settings.item_per_page
    end
  end

  def new
    @book = Book.new
    respond_to do |format|
      format.html {render partial: "book_form", locals: {book: @book}}
    end
  end

  def create
    @book = Book.create book_params
    respond_to do |format|
      if @book.save
        format.html {render @book}
      else
        render json: {errors: @book.errors.full_messages}
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html
    end
  end

  def show
    respond_to do |format|
      format.html {render partial: "edit", locals: {book: @book}}
    end
  end

  def update
    @book.update_attributes book_params
    respond_to do |format|
      format.html {render @book.reload}
    end
  end

  private
  def book_params
    params.require(:book).permit :title, :publish_date, :pages, :category_id,
      :description, :author_id, :publisher_id,
      specifications_attributes: [:id, :specification_name, :specification_value, :_destroy]
  end

  def load_relationships
    @publishers = Publisher.select("id, name")
    @categories = Category.all
    @authors = Author.select("id, name")
  end

end

app/controllers/books_controller.rb
class BooksController<ApplicationController
  include BooksHelper

  before_action :load_book, only: :show

  def index
    @categories = Category.select("id, name")
    @books = Book.select("id, title, slug, category_id").paginate page: params[:page], per_page: Settings.books.page
    if params[:filter]
      @books = filter_by(params[:filter]).paginate page: params[:page], per_page: Settings.books.page
    elsif params[:cate]
      @books = filter_cate(params[:cate]).paginate page: params[:page], per_page: Settings.books.page
    elsif params[:search]
      @books = search_by(params[:search]).paginate page: params[:page], per_page: Settings.books.page
    end
  end

  def show
    @supports = Supports::Book.new @book
  end

end

app/helpers/books_helper.rb
module BooksHelper

  def load_books
    @books = Book.select("id, title, slug, category_id")
  end

  def filter_by val
    case val
    when ""
      load_books
    when "most_rate"
      @most_rate = load_books.sort_by {|b| b.avg_rating}
      @books = @most_rate.reverse!
    when "most_favorites"
      @most_favorites = load_books.sort_by {|b| b.favorited_by.size}
      @books = @most_favorites
    end
  end

  def search_by val
    val ||= ""
    @books = Book.search(val).paginate page: params[:page]
  end

  def filter_cate id
    id ||= ""
    @cate = Category.find_by id: id
    @books = @cate.books.paginate page: params[:page]
  end
end

app/views/admin/books/_book.html.erb
<tr id="<%= dom_id(book) %>">
  <td><%= link_to book.title, book %></td>
  <td><%= book.author.name %></td>
  <td><%= book.pages %></td>
  <td><%= Publisher.find_by(id: book.publisher_id).name %></td>
  <td><%= book.category.name %></td>
  <td>
    <%= link_to admin_book_path(book.id), class: "btn-edit-book" do %>
      <i class="fa fa-pencil-square-o"></i>
    <% end %>
    |
    <%= link_to admin_book_path(book.id), class: "btn-delete" do %>
      <i class="fa fa-times"></i>
    <% end %>
  </td>
</tr>

app/views/admin/books/_book_form.html.erb
<%= form_for @book, url: admin_books_path do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control", required: true %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>

  <%= f.label :publish_date %>
  <%= f.date_field :publish_date, class: "form-control", required: true %>

  <%= f.label :pages %>
  <%= f.number_field :pages, class: "form-control", required: true %>

  <div id="spec">

  </div>
  <%= add_fields t("add_spec"), f, :specifications %>
  <br>
  <br>
  <%= f.label :publisher_id %>
  <%= f.select :publisher_id, @publishers.collect {|c| [c.name, c.id]}, {},
    {required: true, autofocus: true, class: "form-control"} %>

  <%= f.label :author_id %>
  <%= f.select :author_id, @authors.collect {|c| [c.name, c.id]}, {},
    {required: true, autofocus: true, class: "form-control"} %>

  <%= f.label :category_id %>
  <%= f.select :category_id, @categories.collect {|cate| ["#{'—' * cate.depth} #{cate.name}", cate.id]}, {},
    {required: true, autofocus: true, class: "form-control"} %>

  <%= f.submit t("create"), class: "btn btn-primary" %>
<% end %>

app/views/admin/books/_edit.html.erb
<%= form_for @book, url: admin_book_path do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control", required: true %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>

  <%= f.label :publish_date %>
  <%= f.date_field :publish_date, class: "form-control", required: true %>

  <%= f.label :pages %>
  <%= f.number_field :pages, class: "form-control", required: true %>

  <div id="spec">
    <%= f.fields_for :specifications do |builder| %>
      <%= render "specification_fields", f: builder %>
    <% end %>
  </div>
  <%= add_fields t("add_spec"), f, :specifications %>
  <br>
  <br>
  <%= f.label :publisher_id %>
  <%= f.select :publisher_id, @publishers.collect {|c| [c.name, c.id]}, {},
    {required: true, autofocus: true, class: "form-control"} %>

  <%= f.label :author_id %>
  <%= f.select :author_id, @authors.collect {|c| [c.name, c.id]}, {},
    {required: true, autofocus: true, class: "form-control"} %>

  <%= f.label :category_id %>
  <%= f.select :category_id, @categories.collect {|cate| ["#{'—' * cate.depth} #{cate.name}", cate.id]}, {},
    {required: true, autofocus: true, class: "form-control"} %>

  <%= f.submit t("create"), class: "btn btn-warning" %>
<% end %>

app/views/admin/books/_specification_fields.html.erb
<fieldset>
  <div class="row">
    <div class="col-sm-5">
      <%= f.label :specification_name %>
      <%= f.text_field :specification_name, class: "form-control", required: true %>
    </div>

    <div class="col-sm-5">
      <%= f.label :specification_value %>
      <%= f.text_field :specification_value, class: "form-control", required: true %>
    </div>
    <div class="col-sm-2">
      <%= link_to t("remove"), "#", id: "remove_fields" %>
    </div>
  </div>
</fieldset>

app/views/admin/books/index.html.erb
<% provide :title, t("books") %>
<div class="row">
  <div class="col-md-12">
    <h1><%= t "books" %></h1>
  </div>
  <a id="btn-new-book" class="btn btn-success">
    <span>
      <i class="fa fa-plus-square" aria-hidden="true"></i>
    </span> <%= t "new_book" %>
  </a>
  <div class="row">
    <div id="custom-search-input">
      <div class="col-md-12">
        <span><%= t "search_title_author" %></span>
        <%= form_tag admin_books_path, method: :get do%>
          <%= search_field_tag "search", nil, class: "form-control",
            placeholder: t("search") %>
          <%= submit_tag t("search"), class: "btn btn-info", name: nil %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="admin-filter">
    <span><%= t "sort_by" %></span>
      <%= form_tag admin_books_path, method: :get do %>
        <%= select_tag :filter,
          options_for_select(Settings.filters.map{|key, val| [val, key]},
          selected: params[:filter]), class: "form-control filter-sel",
          include_blank: true %>
        <%= submit_tag t("filter"), class: "btn btn-default" %>
      <% end %>
    </div>
    <%= will_paginate %>
    <table id="books" class="table table-bordered table-hover">
      <thead>
        <tr>
          <th><%= t "title" %></th>
          <th><%= t "author" %></th>
          <th><%= t "pages" %></th>
          <th><%= t "publisher" %></th>
          <th><%= t "category" %></th>
          <th><%= t "action" %></th>
        </tr>
      </thead>
      <tbody>
        <%= render @books %>
      </tbody>
    </table>
    <%= will_paginate %>
  </div>
</div>
<br>
<div id="modal-new" class="modal">
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2><%= t "create_new_book" %></h2>
    </div>
    <div class="modal-body">

    </div>
  </div>
</div>
<div id="modal-edit" class="modal modal-edit-book">
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2><%= t "edit_book" %></h2>
    </div>
    <div class="edit-modal-body">

    </div>
  </div>
</div>