config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: "confirmations",
    omniauth_callbacks: "callbacks"
  }

  as :user do
    get "/login" => "devise/sessions#new", as: :login
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy", as: :logout
    get "/signup" => "devise/registrations#new", as: :signup
    post "/signup" => "devise/registrations#create"
  end

  resources :users do
    member do
      get :favorites
      resources :followers, only: :index
      resources :followings, only: :index
      resources :activities, only: :index
    end
  end
  root "static_pages#home"
  namespace :admin do
    resources :books
    resources :categories
    resources :requests, only: [:index, :update, :show]
    resources :authors
    resources :import, only: :create
    resources :publishers
    resources :users
    get "", to: "dashboard#home", as: "/"
  end
  resources :books do
    member do
      resources :borrows, only: [:new, :create]
    end
  end
  resources :favorites, only: [:create, :destroy]
  resources :requests
  resources :categories, only: [:show]
  resources :reviews, except: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :comments, except: :index
  resources :likes, only: [:create, :destroy, :show]
  resources :bookmarks, only: [:create, :update]
  resources :messages, only: [:index]
  resources :chatrooms
  resources :notifications, only: [:index, :update]
  mount ActionCable.server => "/cable"
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :publisher, optional: true
  has_many :books, dependent: :destroy
  validates :name, presence: true, length: {maximum: 150}

end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController
  load_and_authorize_resource
  layout "admin"
  before_action :authenticate_user!

  def index
    @authors = Author.select("id, name, bio").paginate page: params[:page], per_page: Settings.item_per_page
    @author = Author.new
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def update
    respond_to do |format|
      if @author.update_attributes author_params
        format.html {render @author.reload}
      else
        format.html
      end
    end
  end

  def show
    @author_books = @author.books
    cates = @author.books.select("category_id")
    @author_categories = Category.where id: cates
  end

  def edit
    respond_to do |format|
      format.html {render partial: "edit", locals: {author: @author}}
    end
  end

  def create
    @author = Author.new author_params
    respond_to do |format|
      if @author.save
        format.html {render @author}
      else
        format.html
      end
    end
  end

  def destroy
    respond_to do |format|
      if @author.books.any?
        format.js {render status: 500}
      elsif @author.destroy
        format.html
      end
    end
  end

  private

  def author_params
    params.require(:author).permit :name, :bio, :publisher_id
  end

end

app/views/admin/authors/_author.html.erb
<tr id="<%= dom_id(author) %>">
  <td><%= link_to author.name, admin_author_path(author) %></td>
  <td><%= author.bio %></td>
  <td><%= author.books.size %></td>
  <td>
    <%= link_to edit_admin_author_path(author), class: "btn-edit-author" do %>
      <i class="fa fa-pencil-square-o"></i>
    <% end %>
    |
    <%= link_to admin_author_path(author), class: "btn-delete-author" do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </td>
 </tr>

app/views/admin/authors/_author_form.html.erb
<%= form_for @author, url: admin_authors_path, remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", required: true %>

  <%= f.label :bio %>
  <%= f.text_field :bio, class: "form-control" %>

  <%= f.select :publisher_id,
    Publisher.select("id, name").collect {|c| [c.name, c.id]},
    {include_blank: t("no_publisher")},
    {autofocus: true, class: "form-control"} %>

  <%= f.submit t("create"), class: "btn btn-primary" %>
<% end %>

app/views/admin/authors/_edit.html.erb
<%= form_for @author, url: admin_author_path do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", require: true %>

  <%= f.label :bio %>
  <%= f.text_field :bio, class: "form-control" %>

  <%= f.label :publisher_id %>
  <%= f.select :publisher_id,
    Publisher.select("id, name").collect {|c| [c.name, c.id]},
    {include_blank: t("no_publisher")},
    {autofocus: true, class: "form-control"} %>

  <%= f.submit t("update"), class: "btn btn-warning" %>
<% end %>

app/views/admin/authors/index.html.erb
<% provide :title, t("authors") %>
<div class="row">
  <div class="col-md-4">
    <h1><%= t "new_author" %></h1>
    <%= render "author_form" %>
  </div>
  <div class="col-md-4">
    <h1><%= t "upload_author" %></h1>
    <div class="upload">
      <%= form_tag admin_import_index_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= hidden_field_tag :object, "author" %>
        <%= submit_tag t("upload"), class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
  <div class="col-md-4">
    <h1><%= t "download" %></h1>
    <%= link_to admin_authors_path(format: "xlsx") do %>
      <span>
        <i class="fa fa-download" aria-hidden="true"></i>
        <%= t "download_excel" %>
      </span>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-12">
    <h1><%= t "author_list" %></h1>
    <table id="authors" class="table table-bordered table-hover">
      <colgroup>
        <col span="1" style="width: 30%;">
        <col span="1" style="width: 40%;">
        <col span="1" style="width: 15%;">
        <col span="1" style="width: 10%;">
      </colgroup>
      <thead>
        <tr>
          <th><%= t "name" %></th>
          <th><%= t "bio" %></th>
          <th><%= t "books" %></th>
          <th><%= t "action" %></th>
        </tr>
      </thead>
      <tbody id="author-list">
        <%= render @authors %>
      </tbody>
    </table>
    <p class="text-info">
      <%= t "current_author" %> : <%= @authors.length %>
    </p>
  </div>
</div>
<div id="modal-edit-author" class="modal modal-edit-author">
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2><%= t "edit_author" %></h2>
    </div>
    <div class="edit-modal-body">

    </div>
  </div>
</div>

app/views/admin/authors/show.html.erb
<% provide :title, @author.name %>
<div class="container">
  <div class="hidden-xs col-md-3">
    <div class="fading-side-menu" data-spy="affix" data-offset-top="350">
      <h5><%= t "contents" %></h5>
      <hr class="no-margin">
      <ul class="list-unstyled">
        <li>
          <a href="#intro">
            <span class="fa fa-angle-double-right text-primary"></span><%= t "intro" %>
          </a>
        </li>
        <li>
          <a href="#authors">
            <span class="fa fa-angle-double-right text-primary"></span>
            <%= t "authors" %>
          </a>
        </li>
        <li>
          <a href="#books">
            <span class="fa fa-angle-double-right text-primary"></span>
            <%= t "books" %>
          </a>
        </li>
        <li>
          <a href="#categories">
            <span class="fa fa-angle-double-right text-primary"></span>
            <%= t "categories" %>
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div class="col-md-9">
    <h3 id="intro"><%= @author.name %></h3>
    <p><%= @author.bio %></p>
    <hr>
    <h3 id="authors"><%= t "publishers" %></h3>
    <div>
      <p><%= @author.publisher.nil? ? "no publisher" : @author.publisher.name %></p>
    </div>
    <hr>
    <h3 id="books"><%= t "books" %></h3>
    <div>
      <table id="authors" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th><%= t "title" %></th>
            <th><%= t "author" %></th>
            <th><%= t "category" %></th>
          </tr>
        </thead>
        <tbody id="book-list">
          <%= render partial: "admin/publishers/book", collection: @author_books %>
        </tbody>
      </table>
    </div>
    <hr>
    <h3 id="categories"><%= t "categories" %></h3>
    <div>
      <ol>
        <%= render partial: "admin/publishers/category", collection: @author_categories %>
      </ol>
     </div>
  </div>
</div>