config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: "confirmations",
    omniauth_callbacks: "callbacks"
  }

  as :user do
    get "/login" => "devise/sessions#new", as: :login
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy", as: :logout
    get "/signup" => "devise/registrations#new", as: :signup
    post "/signup" => "devise/registrations#create"
  end

  resources :users do
    member do
      get :favorites
      resources :followers, only: :index
      resources :followings, only: :index
      resources :activities, only: :index
    end
  end
  root "static_pages#home"
  namespace :admin do
    resources :books
    resources :categories
    resources :requests, only: [:index, :update, :show]
    resources :authors
    resources :import, only: :create
    resources :publishers
    resources :users
    get "", to: "dashboard#home", as: "/"
  end
  resources :books do
    member do
      resources :borrows, only: [:new, :create]
    end
  end
  resources :favorites, only: [:create, :destroy]
  resources :requests
  resources :categories, only: [:show]
  resources :reviews, except: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :comments, except: :index
  resources :likes, only: [:create, :destroy, :show]
  resources :bookmarks, only: [:create, :update]
  resources :messages, only: [:index]
  resources :chatrooms
  resources :notifications, only: [:index, :update]
  mount ActionCable.server => "/cable"
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :authors, dependent: :destroy
  validates :name, presence: true, length: {maximum: 200}

  scope :total_book, -> {joins(:authors, :books).select("authors.books.title")}

  def total_books
    authors.collect(&:books).flatten
  end

  def total_categories
    authors.collect(&:books).flatten.uniq.collect(&:category)
  end

end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < ApplicationController
  load_and_authorize_resource

  before_action :authenticate_user!

  layout "admin"

  def index
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def new
    @publisher = Publisher.new
    respond_to do |format|
      format.html {render partial: "publisher_form", locals: {publisher: @publisher}}
    end
  end

  def show
    @publisher_authors = @publisher.authors.paginate page: params[:page]
    @publisher_books = @publisher.total_books.paginate page: params[:page]
    @publisher_categories = @publisher.total_categories.paginate page: params[:page]
  end

  def create
    @publisher = Publisher.new publisher_params
    respond_to do |format|
      if @publisher.save
        format.html {render @publisher}
      else
        format.html
      end
    end
  end

  def edit
    respond_to do |format|
      format.html {render partial: "edit", locals: {publisher: @publisher}}
    end
  end

  def update
    respond_to do |format|
      if @publisher.update_attributes publisher_params
        format.html {render @publisher.reload}
      else
        format.html
      end
    end
  end

  def destroy
    respond_to do |format|
      if @publisher.authors.any?
        format.js {render status: 500}
      elsif @publisher.destroy
        format.html
      end
    end
  end

  private
  def publisher_params
    params.require(:publisher).permit :name, :description
  end

end

app/views/admin/publishers/_author.html.erb
<td><%= author.name %></td>
<td><%= author.books.size %></td>

app/views/admin/publishers/_book.html.erb
<tr>
  <td><%= book.title %></td>
  <td><%= book.author.name %></td>
  <td><%= book.category.name %></td>
</tr>

app/views/admin/publishers/_category.html.erb
<li><%= category.name %></li>

app/views/admin/publishers/_edit.html.erb
<%= form_for @publisher, url: admin_publisher_path do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", require: true %>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.submit t("update"), class: "btn btn-warning" %>
<% end %>

app/views/admin/publishers/_publisher.html.erb
<tr id="<%= dom_id(publisher) %>">
  <td><%= link_to publisher.name, admin_publisher_path(publisher) %></td>
  <td id="publisher-author">
    <%= publisher.authors.size %>
  </td>
  <td id="publisher-book">
    <%= publisher.total_books.size %>
  </td>
  <td>
    <span id="publisher-cate">
      <%= publisher.total_categories.size %>
    </span>
  </td>
  <td>
    <%= link_to edit_admin_publisher_path(publisher), class: "btn-edit-publisher" do %>
      <i class="fa fa-pencil-square-o"></i>
    <% end %>
    |
    <%= link_to admin_publisher_path(publisher), class: "btn-delete-publisher" do %>
      <i class="fa fa-trash" aria-hidden="true"></i>
    <% end %>
  </td>
</tr>

app/views/admin/publishers/_publisher_form.html.erb
<%= form_for @publisher, url: admin_publishers_path, remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", required: true %>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.submit t("create"), class: "btn btn-success" %>
<% end %>

app/views/admin/publishers/index.html.erb
<% provide :title, t("publishers") %>
<div class="row">
  <div class="col-md-12">
    <h1><%= t "publishers" %></h1>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-6">
      <h3><%= t "import_excel" %></h3>
      <div class="upload">
        <%= form_tag admin_import_index_path, multipart: true do %>
          <%= file_field_tag :file %>
          <%= hidden_field_tag :object, "publisher" %>
          <%= submit_tag t("upload"), class: "btn btn-success form-inline" %>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <h3><%= t "download_excel" %></h3>
      <div class="import">
        <%= link_to admin_publishers_path(format: "xlsx") do %>
          <span>
            <i class="fa fa-download" aria-hidden="true"></i>
            <%= t "download_excel" %>
          </span>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
  <a id="btn-new-publisher" class="btn btn-primary">
    <span>
      <i class="fa fa-plus-square" aria-hidden="true"></i>
      <%= t "new" %>
    </span>
  </a>
  <table id="publishers" class="table table-bordered table-hover">
    <thead>
      <tr>
        <th><%= t "name" %></th>
        <th><%= t "authors" %></th>
        <th><%= t "books" %></th>
        <th><%= t "categories" %></th>
        <th><%= t "action" %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @publishers %>
    </tbody>
  </table>
</div>
<div id="modal-new" class="modal">
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2><%= t "create_new_publisher" %></h2>
    </div>
    <div class="modal-body">

    </div>
  </div>
</div>
<div id="modal-edit" class="modal modal-edit">
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2><%= t "edit_publisher" %></h2>
    </div>
    <div class="edit-modal-body">

    </div>
  </div>
</div>

app/views/admin/publishers/show.html.erb
<% provide :title, @publisher.name %>
<div class="container">
  <div class="hidden-xs col-md-3">
    <div class="fading-side-menu" data-spy="affix" data-offset-top="350">
      <h5><%= t "contents" %></h5>
      <hr class="no-margin">
      <ul class="list-unstyled">
        <li>
          <a href="#intro">
            <span class="fa fa-angle-double-right text-primary"></span><%= t "intro" %>
          </a>
        </li>
        <li>
          <a href="#authors">
            <span class="fa fa-angle-double-right text-primary"></span>
            <%= t "authors" %>
          </a>
        </li>
        <li>
          <a href="#books">
            <span class="fa fa-angle-double-right text-primary"></span>
            <%= t "books" %>
          </a>
        </li>
        <li>
          <a href="#categories">
            <span class="fa fa-angle-double-right text-primary"></span>
            <%= t "categories" %>
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div class="col-md-9">
    <h3 id="intro"><%= @publisher.name %></h3>
    <p><%= @publisher.description %></p>
    <hr>
    <h3 id="authors"><%= t "authors" %></h3>
    <div>
      <table id="authors" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th><%= t "name" %></th>
            <th><%= t "books" %></th>
          </tr>
        </thead>
        <tbody id="author-list">
          <%= render partial: "author", collection: @publisher_authors %>
        </tbody>
      </table>
      <%= will_paginate @publisher_authors, per_page: Settings.item_per_page %>
    </div>
    <hr>
    <h3 id="books"><%= t "books" %></h3>
    <div>
      <table id="authors" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th><%= t "title" %></th>
            <th><%= t "author" %></th>
            <th><%= t "category" %></th>
          </tr>
        </thead>
        <tbody id="book-list">
          <%= render partial: "book", collection: @publisher_books %>
        </tbody>
      </table>
      <%= will_paginate @publisher_books, per_page: Settings.item_per_page %>
    </div>
    <hr>
    <h3 id="categories"><%= t "categories" %></h3>
    <div>
      <ol>
        <%= render partial: "category", collection: @publisher_categories %>
      </ol>
      <%= will_paginate @publisher_categories, per_page: Settings.item_per_page %>
    </div>
  </div>
</div>