config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: "confirmations",
    omniauth_callbacks: "callbacks"
  }

  as :user do
    get "/login" => "devise/sessions#new", as: :login
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy", as: :logout
    get "/signup" => "devise/registrations#new", as: :signup
    post "/signup" => "devise/registrations#create"
  end

  resources :users do
    member do
      get :favorites
      resources :followers, only: :index
      resources :followings, only: :index
      resources :activities, only: :index
    end
  end
  root "static_pages#home"
  namespace :admin do
    resources :books
    resources :categories
    resources :requests, only: [:index, :update, :show]
    resources :authors
    resources :import, only: :create
    resources :publishers
    resources :users
    get "", to: "dashboard#home", as: "/"
  end
  resources :books do
    member do
      resources :borrows, only: [:new, :create]
    end
  end
  resources :favorites, only: [:create, :destroy]
  resources :requests
  resources :categories, only: [:show]
  resources :reviews, except: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :comments, except: :index
  resources :likes, only: [:create, :destroy, :show]
  resources :bookmarks, only: [:create, :update]
  resources :messages, only: [:index]
  resources :chatrooms
  resources :notifications, only: [:index, :update]
  mount ActionCable.server => "/cable"
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  devise :database_authenticatable, :registerable, :omniauthable,
  :trackable, :validatable, :confirmable, omniauth_providers: [:facebook]
  scope :confirmed, -> {where("confirmed_at IS NOT NULL")}
  scope :unconfirmed, -> {where("confirmed_at IS NULL")}
  scope :all_admin, -> {where("role = 0")}
  scope :all_user, -> {where("role = 1")}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  enum role: [:admin, :user]

  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :borrows, dependent: :destroy
  has_many :active_conversations, class_name: Chatroom.name,
    foreign_key: :host_id, dependent: :destroy
  has_many :passive_conversations, class_name: Chatroom.name,
    foreign_key: :guest_id, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :notifications, foreign_key: :recipient_id

  before_save {self.email = email.downcase}
  before_save :default_role

  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true,
    length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: 6}, allow_nil: true

  def add_favorite book
    favorites.create book_id: book.id
  end

  def remove_favorite book
    if favorited? book
      favorites.find_by(book_id: book.id).destroy
    end
  end

  def favorited? book
    favorites.find_by(book_id: book.id).present?
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  def get_bookmark book
    bookmark = Bookmark.find_by user_id: self.id, book_id: book.id
  end

  def bookmarkeds
    bookmarks = Bookmark.where user_id: self.id
  end

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  private
  def default_role
    self.role ||= :user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!, :admin_user

  load_and_authorize_resource except: [:create]

  layout "admin"

  def index
    @users = User.paginate page: params[:page], per_page: Settings.item_per_page
  end

  def new
    @user = User.new
    respond_to do |format|
      format.html{render partial: "user_form", locals: {user: @user}}
    end
  end

  def create
    @user = User.new user_params
    if params[:skip_confirmation] == "1"
      @user.skip_confirmation!
    end
    if @user.save
      flash[:notice] = t "user_created"
      redirect_back fallback_location: :back
    else
      flash[:alert] = t "user_create_failed"
      redirect_back fallback_location: :back
    end
  end

  def show
    respond_to do |format|
      format.html{render partial: "edit", locals: {user: @user}}
    end
  end

  def update
    @user = User.find_by id: params[:id]
    result = false
    if params[:user][:password].blank?
      result = @user.update_without_password user_params
    else
      result = @user.update_attributes user_params
    end
    if result
      flash[:notice] = t "user_updated"
      redirect_back fallback_location: :back
    else
      flash[:alert] = t "user_update_failed"
      redirect_back fallback_location: :back
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :role
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: :show

  def index
    if params[:search]
      @users = User.search(params[:search]).paginate page: params[:page], per_page: Settings.item_per_page
    else
      @users = User.paginate page: params[:page], per_page: Settings.item_per_page
    end
  end

  def show
    @favorites = @user.favorites.latest
    @followers = @user.followers.paginate page: params[:page]
    @followings = @user.following.paginate page: params[:page]
    @activities = @user.activities.latest.limit(Settings.activities.max_retrived_feed)
    @user_bookmarks = current_user.bookmarks if signed_in?
  end

end

app/views/admin/users/_edit.html.erb
<%= form_for @user, url: admin_user_path do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", readonly: true %>

  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control", readonly: true %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control", readonly: true %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control", readonly: true %>

  <%= f.label :role %>
  <br>
  <%= f.label :role do %>
    <%= f.radio_button :role, :user, checked: true %>
    <span><%= t "user" %></span>
  <% end %>

  <%= f.label :role do %>
    <%= f.radio_button :role, :admin %>
    <span><%= t "admin" %></span>
  <% end %>
  <br>

  <br>
  <%= f.submit t("create"), class: "btn btn-primary" %>
<% end %>

app/views/admin/users/_user.html.erb
<tr id="<%= dom_id(user) %>">
  <td>
    <%= index_for user_counter, @users.current_page, Settings.item_per_page %>
  </td>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.confirmed? ? I18n.t("confirmed") : I18n.t("unconfirmed") %></td>
  <td><%= user.role %></td>
  <td>
    <%= link_to admin_user_path(user), class: "btn-edit-user" do %>
      <i class="fa fa-pencil-square-o"></i>
    <% end %>
  </td>
</tr>

app/views/admin/users/_user_form.html.erb
<%= form_for @user, url: admin_users_path do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", required: true %>

  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control", required: true %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control", required: true %>

  <%= f.label :role %>
  <br>
  <%= f.label :role do %>
    <%= f.radio_button :role, :user, checked: true %>
    <span><%= t "user" %></span>
  <% end %>

  <%= f.label :role do %>
    <%= f.radio_button :role, :admin %>
    <span><%= t "admin" %></span>
  <% end %>
  <br>

  <%= label_tag :skip_confirmation %>
  <%= label_tag :skip_confirmation do %>
    <%= check_box_tag :skip_confirmation %>
  <% end %>
  <br>
  <%= f.submit t("create"), class: "btn btn-primary" %>
<% end %>

app/views/admin/users/index.html.erb
<% provide :title, t("user_list") %>
<div class="container">
  <div class="page-header">
    <h1><%= t "users_manager" %></h1>
  </div>
  <p>
    <%= t "total_user" %>: <span class="badge"><%= @users.size %></span>
  </p>
  <p>
    <%= t "total_confirmed_user" %>:
    <span class="badge"><%= User.confirmed.size %></span>
  </p>
  <p>
    <%= t "total_admin" %>:
    <span class="badge"><%= User.all_admin.size %></span>
  </p>
  <hr>
  <div class="row">
    <div class="col-md-12">
      <div class="btn-toolbar">
        <button id="btn-new-user" class="btn btn-primary">
          <i class="fa fa-plus-square" aria-hidden="true"></i>
          <%= t "new_user" %>
        </button>
        <button class="btn">
          <%= link_to admin_users_path(format: "xlsx") do %>
            <span>
              <i class="fa fa-download" aria-hidden="true"></i>
              <%= t "download_excel" %>
            </span>
          <% end %>
        </button>
        <div class="upload">
          <%= form_tag admin_import_index_path, multipart: true,
            class: "form-inline" do %>
            <div class="form-group">
              <%= file_field_tag :file %>
            </div>
            <%= hidden_field_tag :object, "user" %>
            <%= submit_tag t("upload"), class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-12">
      <div class="well">
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th><%= t "name" %></th>
              <th><%= t "email" %></th>
              <th><%= t "status" %></th>
              <th><%= t "role" %></th>
              <th><%= t "action" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render @users %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<div id="modal-new" class="modal">
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2><%= t "create_new_user" %></h2>
    </div>
    <div class="modal-body">

    </div>
  </div>
</div>
<div id="modal-edit" class="modal modal-edit">
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2><%= t "edit_user" %></h2>
    </div>
    <div class="edit-modal-body">

    </div>
  </div>
</div>